apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-notification
  namespace: ebanking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      containers:
      - name: postgres-notification
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "notification_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: notification.db.password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-notification-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-notification-data
        persistentVolumeClaim:
          claimName: postgres-notification-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: ebanking
spec:
  selector:
    app: postgres-notification
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-notification-pvc
  namespace: ebanking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi